version: '3.8'

services:

  plexdiscordbot:
    build: 
      context: ./plexdiscordbot
      target: prod
    image: plexdiscordbot
    volumes:
      - ./plexdiscordbot/src:/plexdiscordbot
    env_file:
      - .env