version: '3.8'

services:

  plexdiscordbot:
    build: 
      context: ./plexdiscordbot
      target: prod
    image: plexdiscordbot
    volumes:
      - db:/plexdiscordbot/db
    env_file:
      - .env

volumes:
  db: